name: kilo_takibi_getx
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5
  animated_bottom_navigation_bar: ^1.1.0
  intl: ^0.17.0
  json_serializable: ^6.5.1
  font_awesome_flutter: ^10.2.1
  numberpicker: ^2.1.1
  flutter_svg:
  pie_chart:
  image_picker: ^0.8.6
  image_cropper: ^3.0.1
  get_storage: ^2.0.3
  lottie: ^2.0.0
  flutter_native_splash: ^2.2.15


  firebase_core: ^2.3.0
  firebase_database: ^10.0.6
  firebase_auth: ^4.1.5
  cloud_firestore: ^4.1.0
  firebase_storage: ^11.0.7
  file_picker: ^5.2.4



  cupertino_icons: ^1.0.2
  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0
  google_fonts: ^3.0.1
  simple_animations: ^5.0.0+3


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0
  build_runner: ^2.3.0
  freezed: ^2.2.0
  json_serializable: ^6.5.1
  flutter_launcher_icons: ^0.11.0



flutter:


  uses-material-design: true
  assets:
    - assets/icons/
    - assets/Google_Fonts/
    - assets/images/

flutter_icons:
  android: true
  ios: true
  image_path_android: "assets/icons/play_store_512.png"
  image_path_ios: "assets/icons/play_store_512.png"

  fonts:
    - family: RubikMicrobe
      fonts:
        - asset: assets/Google_Fonts/Rubik_Microbe/RubikMicrobe-Regular.ttf

    - family: Josefin
      fonts:
        - asset: assets/Google_Fonts/Josefin_Sans/static/JosefinSans-Bold.ttf